<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.850" timestamp="2025-04-03T11:49:38.134515+01:00" hostname="DESKTOP-GB108BE"><testcase classname="" name="tests.test_models" time="0.000"><error message="collection failure">ImportError while importing test module 'D:\CDEVOPS\Cdevopsmovieapp-main\Cdevopsmovieapp-main\movie_booking\movie_booking_app\movie_booking\tests\test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_models.py:2: in &lt;module&gt;
    from django.contrib.auth.models import User
env\lib\site-packages\django\contrib\auth\models.py:3: in &lt;module&gt;
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
env\lib\site-packages\django\contrib\auth\base_user.py:57: in &lt;module&gt;
    class AbstractBaseUser(models.Model):
env\lib\site-packages\django\db\models\base.py:129: in __new__
    app_config = apps.get_containing_app_config(module)
env\lib\site-packages\django\apps\registry.py:260: in get_containing_app_config
    self.check_apps_ready()
env\lib\site-packages\django\apps\registry.py:137: in check_apps_ready
    settings.INSTALLED_APPS
env\lib\site-packages\django\conf\__init__.py:102: in __getattr__
    self._setup(name)
env\lib\site-packages\django\conf\__init__.py:89: in _setup
    self._wrapped = Settings(settings_module)
env\lib\site-packages\django\conf\__init__.py:217: in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
C:\Program Files\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'movie_booking.settings'</error></testcase></testsuite></testsuites>